// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1mw7RCa5ddo7-VYucMC5jJXh1ZyDhBA',
    appId: '1:959796329620:web:1da791a90227b31b76c881',
    messagingSenderId: '959796329620',
    projectId: 'nutrimind-main',
    authDomain: 'nutrimind-main.firebaseapp.com',
    storageBucket: 'nutrimind-main.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp1mw7RCa5ddo7-VYucMC5jJXh1ZyDhBA',
    appId: '1:959796329620:web:ceb2310cab076d6b76c881',
    messagingSenderId: '959796329620',
    projectId: 'nutrimind-main',
    authDomain: 'nutrimind-main.firebaseapp.com',
    storageBucket: 'nutrimind-main.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NeQ4TBj2ilDQ2w586Zf8fzyoQJFpfwg',
    appId: '1:959796329620:android:6bb885c34cbb523f76c881',
    messagingSenderId: '959796329620',
    projectId: 'nutrimind-main',
    storageBucket: 'nutrimind-main.firebasestorage.app',
  );

}