// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAec4rx0qxB7WJdydlgd70NOH9vkJ5LbBc',
    appId: '1:937676159063:web:03f9f4328a4cb17db98b12',
    messagingSenderId: '937676159063',
    projectId: 'nutrimind-20f1d',
    authDomain: 'nutrimind-20f1d.firebaseapp.com',
    storageBucket: 'nutrimind-20f1d.firebasestorage.app',
    measurementId: 'G-SN9BWH42J5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAec4rx0qxB7WJdydlgd70NOH9vkJ5LbBc',
    appId: '1:937676159063:web:1e8d54d90e209f3db98b12',
    messagingSenderId: '937676159063',
    projectId: 'nutrimind-20f1d',
    authDomain: 'nutrimind-20f1d.firebaseapp.com',
    storageBucket: 'nutrimind-20f1d.firebasestorage.app',
    measurementId: 'G-3Z99R5KXEN',
  );

}